version: "3"

services:
  ui:
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080
    volumes:
      - ./openapi:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/protocollo-aoo.yaml
